---
title: "Contrastive symmetry"
output: html_document
---

```{r init, include=FALSE, cache=FALSE}
library(reshape2)
library(plyr)
library(ggplot2)
library(dplyr)
library(pryr)
library(magrittr)
library(foreach)
library(doParallel)
library(parallel)
library(xtable)

source("src/R/util.R")
source("src/R/read.R")
source("src/R/auc.R")
source("src/R/plot.R")
source("src/R/stats.R")
```

```{r read-input, include=FALSE, cache=TRUE}
source("analysis/file_locations.R")
source("analysis/read_input.R")
source("analysis/build_stats.R")
```

```{r melt-stats, include=FALSE, cache=TRUE}
inv_stats_melted <- melt(inv_stats,
                         id.vars=c("segment_type", "inventory_type", "language"),
                         measure.vars=c("Econ", "Loc", "Glob"),
                         variable.name="measure_type",
                         value.name="Measure")
```

#Study 1

```{r hist-all,echo=TRUE, fig.width=12, fig.height=6, dev='quartz_pdf'}
palette_ <- c(Natural=DARK_BLUE, Control=LIGHT_ORANGE)
d <- filter(inv_stats, inventory_type %in% c("Natural", "Control"))
d$inventory_type <- factor(d$inventory_type, levels=c("Control", "Natural"))
p1 <- plot_prevalence_with_mean_facet(d, "Econ", "inventory_type",
                                      "segment_type",
                                      palette_,
                                      var_group_name="") +
      theme_bw() +
      theme(text=element_text(family="Times", size=24, colour="black"),
            axis.text=element_text(colour="black"), legend.position="none")
p2 <- plot_prevalence_with_mean_facet(d, "Loc", "inventory_type",
                                      "segment_type",
                                      palette_,
                                      var_group_name="") +
      theme_bw() +
      theme(text=element_text(family="Times", size=24, colour="black"),
            axis.text=element_text(colour="black"), legend.position="none")
p3 <- plot_prevalence_with_mean_facet(d, "Glob", "inventory_type",
                                      "segment_type",
                                      palette_,
                                      var_group_name="") +
      theme_bw() +
      theme(text=element_text(family="Times", size=24, colour="black"),
            axis.text=element_text(colour="black"), legend.position="bottom")
print(p1)
print(p2)
print(p3)
```


```{r all-rocs,echo=TRUE, fig.width=12, fig.height=9, dev='quartz_pdf'}
palette_ <- c(Vowel=DARKEST_MAROON, Stop=DARK_BLUE,
              Whole=LIGHTEST_BLUE, Consonant=LIGHT_BROWN)
d <- filter(inv_stats_melted, inventory_type %in% c("Natural", "Control"))
d$inventory_type <- factor(d$inventory_type, levels=c("Control", "Natural"))
rocs <- ddply(d, .(segment_type, measure_type),
              function(dd) pred_stats(dd$Measure, dd$inventory_type))
p <- ggplot(rocs, aes(x=fpr, y=tpr)) +
       geom_abline(slope=1.0, intercept=0.0, linetype="dashed", size=0.5) +
       geom_line(size=1) +
       theme_bw() +
       theme(legend.position="bottom",
             text=element_text(family="Times", size=24, colour="black"),
             axis.text=element_text(colour="black"),
             axis.text.x=element_text(angle=90)) +
       ylim(c(0,1)) + 
       xlab("False positive rate") + ylab("True positive rate") +
       scale_colour_manual(values=palette_) +
       facet_grid(measure_type ~ segment_type) 
print(p)
```


#Study 2

```{r rcomp,echo=FALSE, fig.width=12, fig.height=12, dev='quartz_pdf'}
palette_ <- c(Uniform=DARK_MAROON, Natural=DARK_BLUE, Weighted=LIGHTEST_GREEN,
              Control=LIGHT_ORANGE)
d_means <- ddply(inv_stats_melted, .(segment_type, inventory_type, measure_type),
                 summarize, mean_measure=mean(Measure))
d_random <- filter(d_means,
                   inventory_type %in% c("Control", "Uniform", "Weighted"))
d_natural <- filter(d_means, inventory_type=="Natural")
p <- ggplot(d_random, aes(y=mean_measure, x=0, fill=inventory_type)) +
  geom_bar(position="dodge", stat="identity", colour="black") +
  geom_hline(data=d_natural, aes(yintercept=mean_measure),
             colour=palette_["Natural"], lwd=1.5) +
  scale_fill_manual(values=palette_) +
  facet_grid(measure_type ~ segment_type) +
  ylab("Mean value of measure") + 
  guides(fill=guide_legend(title="")) +
  theme_bw() +
  theme(legend.position="bottom",
        text=element_text(family="Times", size=24, colour="black"),
        axis.text=element_text(colour="black"),
        axis.title.x=element_blank(), axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.grid.minor.x=element_blank())
print(p)
```

#AUC and mean table

```{r new-aucs, include=F, cache=T}
bootstrap_auc <- function(left_right, d, var_measure, var_group, var_others) {
  left <- left_right[1]
  right <- left_right[2]
  dd <- filter(d, d[[var_group]] %in% c(left, right))
  auc_sample <- ddply(dd, var_others,
                      .fun=partial(bootstrap, N=10000,
                             FUN=partial(auc_by, measure=var_measure,
                                         classes=var_group, goldleft=left)),
                      .parallel=T)
  auc_sample_melted <- melt(auc_sample)
  result <- ddply(auc_sample_melted, var_others,
                  function(d) data.frame(AUC025=quantile(d$value, 0.025),
                                         AUC500=quantile(d$value, 0.5),
                                         AUC975=quantile(d$value, 0.975)))
}
auc_comparisons <- list(CN=c("Control", "Natural"),
                        CW=c("Control", "Weighted"),
                        CU=c("Control", "Uniform"),
                        WU=c("Weighted", "Uniform"))
registerDoParallel()
aucs_by_comparison <- llply(auc_comparisons, bootstrap_auc,
                            inv_stats_melted, "Measure", "inventory_type",
                            c("segment_type", "measure_type"),
                            .parallel=T)
```

```{r auc-table, include=T, cache=F, results="asis"}
aucs_long <- ldply(aucs_by_comparison, .id="Comparison")
aucs <- reshape(aucs_long, direction="wide", timevar ="segment_type",
                idvar=c("Comparison", "measure_type"))
aucs <- aucs[order(aucs$measure_type),-which(grepl("AUC500", names(aucs)))]
print(xtable(aucs), type="html", include.rownames = F)
```

```{r mean-table, include=T, cache=F, results="asis"}
means_long <- ddply(inv_stats_melted, .(inventory_type, measure_type,
                                        segment_type),
                    summarize, mean_measure=mean(Measure))
means <- reshape(means_long, direction="wide", timevar ="segment_type",
                idvar=c("inventory_type", "measure_type"))
means <- means[order(means$measure_type),]
print(xtable(means), type="html", include.rownames = F)
```