---
title: "Feature economy analysis"
output: html_document
---

```{r init, include=FALSE, cache=FALSE}
library(plyr)
library(ggplot2)
source("../src/analysis/util.R")
source("../src/analysis/read.R")
source("../src/analysis/plot.R")
source("../src/analysis/stats.R")
source("../src/analysis/auc.R")
```

```{r setup, include=FALSE, cache=FALSE}
source("what_analysis.R")
```

```{r read-input, include=FALSE, cache=TRUE}
long_raw_cstats <- read_from_filename_table(CSTATS_FILENAME_TABLE)
short_raw_cstats <- combine_dlist(apply_dlist(long_raw_cstats, undetail))
summary_cstats <- add_cstats(short_raw_cstats)
summary_mcstats <- add_opt_cstats(summary_cstats)
summary_mcstats_multirandom <- multi_random(summary_mcstats)
raw_features <- read_from_filename_table(INVENTORIES_FILENAME_TABLE,
                                         read_feature_table)
summary_fstats <- combine_dlist(apply_dlist(raw_features, compute_fstats_pair))
summary_fstats_multirandom <- multi_random(summary_fstats)
summary_fstats_sing <- combine_dlist(apply_dlist(raw_features, compute_fstats_sing))
summary_fstats_sing_multirandom <- multi_random(summary_fstats_sing)
```

Exact replication of Mackie and Mielke (2011)
---------------------------------------------

```{r exact-replication,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_mcstats[summary_mcstats$segment_type=="Whole",],
                "Random Segment")
p <- plot_prevalence(d, "best_nseg_by_ncfeat", "inventory_type",
                "Number of Segments/Minimum Number of Features",
                "Inventory Type", 
                binwidth=0.15) +
                coord_cartesian(xlim=c(1, 8))
print(p)
```

```{r exact-replication-natural,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_mcstats[summary_mcstats$segment_type=="Whole" &
                     summary_mcstats$inventory_type=="Natural",]
p <- plot_prevalence(d, "best_nseg_by_ncfeat", NULL,
                "Number of Segments/Minimum Number of Features",
                "Inventory Type", 
                colour_palette=default_colour_palette["Natural"],
                binwidth=0.15) +
                coord_cartesian(xlim=c(1, 8))
print(p)
```

```{r exact-replication-random,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_mcstats[summary_mcstats$segment_type=="Whole" &
                     summary_mcstats$inventory_type=="Random Segment",]
p <- plot_prevalence(d, "best_nseg_by_ncfeat", NULL,
                "Number of Segments/Minimum Number of Features",
                "Inventory Type",
                colour_palette=default_colour_palette["Random"],
                binwidth=0.15) + 
                coord_cartesian(xlim=c(1, 8))
print(p)
```

Correction with 2<sup>k</sup> denominator
-----------------------------------------

```{r exact-2-replication,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_mcstats[summary_mcstats$segment_type=="Whole",],
                "Random Segment")
p <- plot_prevalence(d, "best_nseg_by_2_ncfeat", "inventory_type",
                "Number of Segments/Minimum Number of Features",
                "Inventory Type"
                )
print(p)
```

Extension to sub-inventories
----------------------------

```{r subinventories,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_mcstats[summary_mcstats$segment_type!="Whole",],
                "Random Segment")
p <- plot_prevalence(d, "best_nseg_by_2_ncfeat", "inventory_type",
                "Number of Segments/Number of Possible Segments",
                "Inventory Type")
p <- p + facet_grid(segment_type ~.)
print(p)
```

```{r subinventories-means,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_mcstats, "Random Segment")
d$segment_type <- factor(d$segment_type, levels=c("Whole", "Consonant",
                                                  "Stop", "Vowel"))
p <- plot_means(d, "best_nseg_by_2_ncfeat", "inventory_type",
                "Economy", "Inventory Type") +
     facet_grid(~ segment_type) +
     theme(axis.title.x=element_blank(), axis.text.x=element_blank())
print(p)
```

```{r subinventories-aucs,echo=TRUE}
d <- one_random(summary_mcstats, "Random Segment")
ddply(d, .(segment_type),
      .fun=partial(auc_by_inventory_type, measure="best_nseg_by_2_ncfeat"))
```

SBI measure
-----------

```{r sbi-whole,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_cstats[summary_cstats$segment_type=="Whole",],
                "Random Segment")
p <- plot_prevalence(d, "sbi_norm", "inventory_type",
                "Balance", "Inventory Type") +
                coord_cartesian(xlim=c(0, 1))
print(p)
```

```{r sbi-sub,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_cstats[summary_cstats$segment_type!="Whole",],
                "Random Segment")
p <- plot_prevalence(d, "sbi_norm", "inventory_type",
                "Balance", "Inventory Type")
p <- p + facet_grid(segment_type ~ .)
print(p)
```

```{r sbi-means,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_cstats, "Random Segment")
d$segment_type <- factor(d$segment_type, levels=c("Whole", "Consonant",
                                                  "Stop", "Vowel"))
p <- plot_means(d, "sbi_norm", "inventory_type",
                "Balance", "Inventory Type") +
     facet_grid(~ segment_type) +
     theme(axis.title.x=element_blank(), axis.text.x=element_blank())
print(p)
```

```{r sbi-economy-means,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_cstats, "Random Segment")
d$segment_type <- factor(d$segment_type, levels=c("Whole", "Consonant",
                                                  "Stop", "Vowel"))
p <- plot_means(d, "sbi_economy_binned", "inventory_type",
                "Balance z-score by economy level", "Inventory Type") +
     facet_grid(~ segment_type) +
     theme(axis.title.x=element_blank(), axis.text.x=element_blank())
print(p)
```

```{r sbi-economy-means-bysize,echo=FALSE, fig.width=30, fig.height=15}
d <- one_random(summary_cstats, "Random Segment")
d$segment_type <- factor(d$segment_type, levels=c("Whole", "Consonant",
                                                  "Stop", "Vowel"))
p <- plot_means(d, "sbi_economy_binned", "inventory_type",
                "Balance z-score by economy level", "Inventory Type",
                x_var="nseg", x_var_label="Number of segments in inventory") +
     facet_grid(~ segment_type) +
     theme(axis.title.x=element_blank(), axis.text.x=element_blank())
print(p)
```


```{r sbi-aucs,echo=TRUE, cache=TRUE}
d <- one_random(summary_cstats, "Random Segment")
ddply(d, .(segment_type),
      .fun=partial(auc_by_inventory_type, measure="sbi_norm"))
```

```{r sbi-economy-aucs,echo=TRUE, fig.width=30, fig.height=15, cache=TRUE}
d <- one_random(summary_cstats, "Random Segment")
ddply(d, .(segment_type),
      .fun=partial(auc_by_inventory_type, measure="sbi_economy_binned"))
```

Change with respect to baseline
-------------------------------
        
```{r change-baseline-economy-means,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_mcstats
d$inventory_type <- factor(d$inventory_type, levels=c("Natural",
                                                      "Random Segment",
                                                      "Random Feature",
                                                      "Random Matrix"))
d$segment_type <- factor(d$segment_type, levels=c("Whole", "Consonant",
                                                      "Stop",
                                                      "Vowel"))
p <- plot_means(d, "best_nseg_by_2_ncfeat", "inventory_type",
                     "Number of Segments/Number of Possible Segments",
                     "Inventory Type", palette = random_types_palette
                    )
p <- p + facet_grid(~ segment_type) +
  theme(axis.text.x=element_blank()) + coord_cartesian(ylim=c(0, 0.65))
print(p)
```

```{r change-baseline-economy-means-hide-both,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_mcstats
d$inventory_type <- factor(d$inventory_type, levels=c("Natural",
                                                      "Random Segment",
                                                      "Random Feature",
                                                      "Random Matrix"))
d$segment_type <- factor(d$segment_type, levels=c("Whole", "Consonant",
                                                      "Stop",
                                                      "Vowel"))
d$best_nseg_by_2_ncfeat[d$inventory_type %in% c("Random Feature",
                                                "Random Matrix")] <- 0
p <- plot_means(d, "best_nseg_by_2_ncfeat", "inventory_type",
                     "Number of Segments/Number of Possible Segments",
                     "Inventory Type", palette = random_types_palette
                    )
p <- p + facet_grid(~ segment_type) +
  theme(axis.text.x=element_blank()) + coord_cartesian(ylim=c(0, 0.65))
print(p)
```

```{r change-baseline-economy-means-hide-one,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_mcstats
d$inventory_type <- factor(d$inventory_type, levels=c("Natural",
                                                      "Random Segment",
                                                      "Random Feature",
                                                      "Random Matrix"))
d$segment_type <- factor(d$segment_type, levels=c("Whole", "Consonant",
                                                      "Stop",
                                                      "Vowel"))
d$best_nseg_by_2_ncfeat[d$inventory_type %in% c("Random Matrix")] <- 0
p <- plot_means(d, "best_nseg_by_2_ncfeat", "inventory_type",
                     "Number of Segments/Number of Possible Segments",
                     "Inventory Type", palette = random_types_palette
                    )
p <- p + facet_grid(~ segment_type) +
  theme(axis.text.x=element_blank()) + coord_cartesian(ylim=c(0, 0.65))
print(p)
```

Feature bias
------------

```{r feature-avg-means-random,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_fstats_sing[summary_fstats_sing$inventory_type %in%
                           RANDOM_TYPES &
                         summary_fstats_sing$segment_type == "Consonant",]
p <- plot_means(d, "absmean", "inventory_type",
                     "Feature imbalance",
                     "Inventory Type", x_var="nseg",
                     x_var_label="Number of segments in inventory",
                     palette = random_types_palette) +
  coord_cartesian(ylim=c(0, 0.65))
print(p)
```

```{r feature-avg-means,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_fstats_sing[summary_fstats_sing$segment_type == "Consonant",]
p <- plot_means(d, "absmean", "inventory_type",
                     "Feature imbalance",
                     "Inventory Type", x_var="nseg",
                     x_var_label="Number of segments in inventory",
                     palette = random_types_palette) +
  coord_cartesian(ylim=c(0, 0.65))
print(p)
```

```{r feature-avg-means-stops,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_fstats_sing[summary_fstats_sing$segment_type == "Stop",]
p <- plot_means(d, "absmean", "inventory_type",
                     "Feature imbalance",
                     "Inventory Type", x_var="nseg",
                     x_var_label="Number of segments in inventory",
                     palette = random_types_palette) +
  coord_cartesian(ylim=c(0, 0.65))
print(p)
```

```{r feature-avg-means-vowels,echo=FALSE, fig.width=30, fig.height=15}
d <- summary_fstats_sing[summary_fstats_sing$segment_type == "Vowel",]
p <- plot_means(d, "absmean", "inventory_type",
                     "Feature imbalance",
                     "Inventory Type", x_var="nseg",
                     x_var_label="Number of segments in inventory",
                     palette = random_types_palette) +
  coord_cartesian(ylim=c(0, 0.65))
print(p)
```

