CSTATS_FILENAME_TABLE <- data.frame(
  filename=c("../contrast_stats/inv_random_feature_cstats.csv",
             "../contrast_stats/inv_random_segment_cstats.csv",
             "../contrast_stats/inv_random_matrix_cstats.csv",
             "../contrast_stats/inv_cstats.csv",
             "../contrast_stats/cons_random_feature_cstats.csv",
             "../contrast_stats/cons_random_segment_cstats.csv",
             "../contrast_stats/cons_random_matrix_cstats.csv",
             "../contrast_stats/cons_cstats.csv",             
             "../contrast_stats/stop_random_feature_cstats.csv",
             "../contrast_stats/stop_random_segment_cstats.csv",
             "../contrast_stats/stop_random_matrix_cstats.csv",
             "../contrast_stats/stop_cstats.csv",             
             "../contrast_stats/vowel_random_feature_cstats.csv",
             "../contrast_stats/vowel_random_segment_cstats.csv",
             "../contrast_stats/vowel_random_matrix_cstats.csv",
             "../contrast_stats/vowel_cstats.csv"             
             ),
  segment_type=c("Whole", "Whole", "Whole", "Whole",
             "Consonant", "Consonant", "Consonant", "Consonant",
             "Stop", "Stop", "Stop", "Stop",
             "Vowel", "Vowel", "Vowel", "Vowel"),
  inventory_type=c("Random Feature", "Random Segment", "Random Matrix",
                   "Natural",
                   "Random Feature", "Random Segment", "Random Matrix",
                   "Natural", 
                   "Random Feature", "Random Segment", "Random Matrix",
                   "Natural", 
                   "Random Feature", "Random Segment", "Random Matrix",
                   "Natural")
)

INVENTORIES_FILENAME_TABLE <- data.frame(
  filename=c("../data/inv_random_feature.csv",
             "../data/inv_random_segment.csv",
             "../data/inv_random_matrix.csv",
             "../data/inv.csv",
             "../data/cons_random_feature.csv",
             "../data/cons_random_segment.csv",
             "../data/cons_random_matrix.csv",
             "../data/cons.csv",             
             "../data/stop_random_feature.csv",
             "../data/stop_random_segment.csv",
             "../data/stop_random_matrix.csv",
             "../data/stop.csv",             
             "../data/vowel_random_feature.csv",
             "../data/vowel_random_segment.csv",
             "../data/vowel_random_matrix.csv",
             "../data/vowel.csv"             
             ),
  segment_type=c("Whole", "Whole", "Whole", "Whole",
             "Consonant", "Consonant", "Consonant", "Consonant",
             "Stop", "Stop", "Stop", "Stop",
             "Vowel", "Vowel", "Vowel", "Vowel"),
  inventory_type=c("Random Feature", "Random Segment", "Random Matrix",
                   "Natural",
                   "Random Feature", "Random Segment", "Random Matrix",
                   "Natural", 
                   "Random Feature", "Random Segment", "Random Matrix",
                   "Natural", 
                   "Random Feature", "Random Segment", "Random Matrix",
                   "Natural")
)
